### ISSUE TITLE
目前我接入发现的几个问题

### ISSUE THREAD

**Issue by chenxianqi** [v7lin/fake_push#11]
version： lastVersion
测试机： 小米Note7（华为&ios未测试，待测试完毕反馈）
1.前台，后台点击通知栏都不会有回调
2.进程被杀掉后，还是没有走厂商通道发送，再次启动才收到（我去小米后台推送，能收到）

厂商通道已经打开，这是设备注册日志
![image](https://user-images.githubusercontent.com/27764334/60778171-713cee00-a168-11e9-9922-1d585c0d9f91.png)

**Comment by v7lin** [comment]
厂商通道到达速度有时候不会那么快，多推几条。
另外，检查一下以下几项
是用0.5.0版本么？
信鸽后台配置小米和华为渠道了吗？
信鸽后台测试推送能到达吗？

**Comment by chenxianqi** [comment]
版本：0.5.0
信鸽后台（信鸽通道）的可以收到
信鸽后台已经配置了厂商通道
![image](https://user-images.githubusercontent.com/27764334/60782927-05b04c00-a17b-11e9-9fe5-cb88e70a3ef4.png)

**Comment by chenxianqi** [comment]
我已经测试好多次了，去小米后台推送基本不用半分钟就收到了
这个证明小米sdk是继承成功的

**Comment by v7lin** [comment]
你在example上配置你的推送配置和package那么，然后用信鸽推送后台试试看

**Comment by chenxianqi** [comment]
好的，我下午测试，然后反馈

**Comment by chenxianqi** [comment]
已在你的example上测试，也是无法推送到的，只有信鸽通道正常

**Comment by chenxianqi** [comment]
IOS下点击通知栏也没有回调

**Comment by v7lin** [comment]
华为／小米设备上测试均能收到消息并正常打开，收到消息并不会及时。今天测试，小米十几分钟后就能收到，华为半个小时后收到。release测试的时候，几分钟内就能收到。

**Comment by chenxianqi** [comment]
> 华为／小米设备上测试均能收到消息并正常打开，收到消息并不会及时。今天测试，小米十几分钟后就能收到，华为半个小时后收到。release测试的时候，几分钟内就能收到。

我明天在测试看看，也太慢了，哈哈，谁测试环境能等半小时以上

**Comment by chenxianqi** [comment]
> 华为／小米设备上测试均能收到消息并正常打开，收到消息并不会及时。今天测试，小米十几分钟后就能收到，华为半个小时后收到。release测试的时候，几分钟内就能收到。
你测试的是走厂商吗

**Comment by v7lin** [comment]
添加测试设备，针对Token推送，应该会快一点。

**Comment by chenxianqi** [comment]
我就是添加的测试设备，单推的

**Comment by v7lin** [comment]
信鸽工作机制，有接入厂商通道，在厂商手机上只会使用厂商通道。比如华为手机上，不论手机离线或在线，只会周华为厂商推送。测试必须是离线／在线都测试。

**Comment by chenxianqi** [comment]
点击进APP的回调有测试么？貌似没执行，IOS也一样

**Comment by v7lin** [comment]
Android 高级设置，客户端自定义 fake_push://v7lin.github.io/notify_detail?param1=aa&param2=bb，回掉参数通过 uri 传入

**Comment by v7lin** [comment]
认真读 README.md，上面还有链接

**Comment by chenxianqi** [comment]
这个我知道，但是当第一次，执行会弹出一个类似打开url的机制，会重开一个APP进程（小米）

**Comment by v7lin** [comment]
整个工程。认真看两个文件，一个是 README.md，一个是 push.dart，都是小文件

**Comment by v7lin** [comment]
并不会新开一个APP进程

**Comment by chenxianqi** [comment]
我都看了，基本流程都了解，我前几天测试，就好像打开了两个app，关闭一个一个还在，我明天在看看啊什么导致这种现象吧

**Comment by v7lin** [comment]
你将 manifest.xml 里面的 mainactivity 配置信息发我。push工程是按flutter标准工程 lanchmode 为 singleTop 方式接入的。傻瓜式接入。

**Comment by chenxianqi** [comment]
> `

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
--
xmlns:tools="http://schemas.android.com/tools"
package="com.cmp520.WanChe">
 

<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />​
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.VIBRATE"/>
<uses-permission android:name="android.permission.WRITE_SETTINGS" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.RECEIVE_USER_PRESENT" />
<uses-permission android:name="android.permission.GET_TASKS"/>
 
 


<uses-permission android:name="com.cmp520.WanChe.permission.MIPUSH_RECEIVE" />
<permission
android:name="com.cmp520.WanChe.permission.MIPUSH_RECEIVE"
android:protectionLevel="signature" />
<uses-permission android:name="com.cmp520.WanChe.permission.MIPUSH_RECEIVE" />
 

<application
android:name="io.flutter.app.FlutterApplication"
android:label="玩车头条"
tools:replace="android:label"
android:networkSecurityConfig="@xml/network_security_config"
android:icon="@mipmap/ic_launcher">
<activity
android:name="wanche.com.MainActivity"
android:launchMode="singleTop"
android:theme="@style/LaunchTheme"
android:configChanges="orientation\|keyboardHidden\|keyboard\|screenSize\|locale\|layoutDirection\|fontScale\|screenLayout\|density"
android:hardwareAccelerated="true"
android:windowSoftInputMode="adjustResize">

 
<meta-data
android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
android:value="true" />
<intent-filter>
<action android:name="android.intent.action.MAIN"/>
<category android:name="android.intent.category.LAUNCHER"/>
</intent-filter>
 

<intent-filter>
<action android:name="android.intent.action.VIEW" />
<category android:name="android.intent.category.DEFAULT" />
<category android:name="android.intent.category.BROWSABLE" />
<data
android:scheme="wanche"
android:host="com.cmp520.app" />
</intent-filter>
 
 
</activity>
<meta-data
android:name="com.amap.api.v2.apikey"
android:value="4152d781b36233932d77b995fdb76bde64"/>
<provider
android:name="androidx.core.content.FileProvider"
android:authorities="${applicationId}.fileProvider"
android:exported="false"
android:grantUriPermissions="true"
tools:replace="android:authorities">
<meta-data
android:name="android.support.FILE_PROVIDER_PATHS"
android:resource="@xml/filepaths"
tools:replace="android:resource" />
</provider>
 
 
 
</application>
</manifest>

`

**Comment by v7lin** [comment]
看上去并没有问题。

**Comment by chenxianqi** [comment]
IOS下点击通知也没有响应的呢

**Comment by chenxianqi** [comment]
> 这个我知道，但是当第一次，执行会弹出一个类似打开url的机制，会重开一个APP进程（小米）

这个的重现是，当前APP在前台的前提下，去点击通知栏，就知道了

**Comment by chenxianqi** [comment]
> > 这个我知道，但是当第一次，执行会弹出一个类似打开url的机制，会重开一个APP进程（小米）
> 
> 这个的重现是，当前APP在前台的前提下，去点击通知栏，就知道了

我也不知道这个是什么问题，应该不是插件问题，可能和小米定制系统有关

**Comment by v7lin** [comment]
你把 singleTop 改成 singleTask 试试

**Comment by v7lin** [comment]
按说不会，singleTop + clearTop 效果等价于 singleTask.

**Comment by chenxianqi** [comment]
好的，我明天试试看，谢谢您的耐心解答

**Comment by v7lin** [comment]
iOS也能正常接收消息和打开消息。

**Comment by chenxianqi** [comment]
我等了几个小时，都没收到，好尴尬，一打开APP就来了，去小米后台也很快来
