### ISSUE TITLE
Debug正常，release闪退

### ISSUE THREAD

**Issue by FerdiCX** [v7lin/fake_push#13]
flutter运行debug的时候正常工作，使用flutter build apk打release版本闪退，测试example打release版本也是闪退

**Comment by v7lin** [comment]
是打开就闪退，还是接收信息闪退，亦或其他情况闪退

**Comment by v7lin** [comment]
还有flutter版本信息以及啥手机？

**Comment by FerdiCX** [comment]
打开就闪退，使用的小米MIX和华为 Meta20 pro，Flutter是hotfix版本，用你提供的example试了一下也是闪退，用androidstudio run可以烧到手机上，用flutter build apk打出来的release版本就打开闪退



------------------ 原始邮件 ------------------
发件人: "林恒龙"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 凌晨3:06
收件人: "v7lin/fake_push"<fake_push@noreply.github.com>; 
抄送: "废帝"<276336882@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [v7lin/fake_push] Debug正常，release闪退 (#13)




还有flutter版本信息以及啥手机？

**Comment by v7lin** [comment]
buildTypes {
        release {
            ndk {
                abiFilters "armeabi-v7a"
            }
        }
    }

**Comment by FerdiCX** [comment]
> ```
> buildTypes {
>     release {
>         ndk {
>             abiFilters "armeabi-v7a"
>         }
>     }
> }
> ```

解决了，感谢！
