### ISSUE TITLE
Android 通知推送，信鸽原本的customContent被丢弃了

### ISSUE THREAD

**Issue by yuan1809** [v7lin/fake_push#17]
这个函数处理通知推送时，将信鸽推送原本携带的customContent丢弃了。

public static void receiveNotification(Context context, XGPushShowedResult message) {
        Map<String, Object> map = new HashMap<>();
        map.put(FakePushPlugin.ARGUMENT_KEY_RESULT_TITLE, message.getTitle());
        map.put(FakePushPlugin.ARGUMENT_KEY_RESULT_CONTENT, message.getContent());
        Map<String, Object> dest = new HashMap<>();
        // 信鸽BUG？
        // 华为通道 notificationActionType = 1
        // 信鸽通道 notificationActionType = 3
        Uri uri = null;
        if (message.getPushChannel() == PUSH_CHANNEL_XIAOMI && message.getNotificationActionType() == XGPushShowedResult.NOTIFICATION_ACTION_ACTIVITY) {
            Map<String, Object> customContent = JsonUtils.toMap(message.getCustomContent());
            Object intentUri = customContent.get("intent_uri");
            if (intentUri != null && intentUri instanceof String) {
                uri = Uri.parse((String) intentUri);
            }
        } else if (message.getPushChannel() == PUSH_CHANNEL_XINGE && message.getNotificationActionType() == XGPushShowedResult.NOTIFICATION_ACTION_INTENT) {
            uri = Uri.parse(message.getActivity());
        }
        if (uri != null) {
            Set<String> keys = uri.getQueryParameterNames();
            if (keys != null && !keys.isEmpty()) {
                for (String key : keys) {
                    if (!TextUtils.isEmpty(key)) {
                        List<String> values = uri.getQueryParameters(key);
                        if (values != null && !values.isEmpty()) {
                            if (values.size() == 1) {
                                dest.put(key, values.get(0));
                            } else {
                                dest.put(key, values);
                            }
                        }
                    }
                }
            }
        }
        map.put(FakePushPlugin.ARGUMENT_KEY_RESULT_CUSTOMCONTENT, JsonUtils.toJson(dest));

        Intent receiver = new Intent();
        receiver.setAction(ACTION_RECEIVE_NOTIFICATION);
        receiver.putExtra(KEY_EXTRA_MAP, JsonUtils.toJson(map));
        receiver.setPackage(context.getPackageName());
        context.sendBroadcast(receiver);
    }

**Comment by v7lin** [comment]
请认真阅读readme.md
