### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by BugsBunnyBR** [v7lin/fake_push#18]
Hey, how about to migrate to AndroidX libraries?

**Comment by v7lin** [comment]
It supports AndroidX

**Comment by BugsBunnyBR** [comment]
No, it does not!
https://github.com/v7lin/fake_push/blob/master/android/build.gradle#L48
When an app project is already migrated to AndroidX, this plugin will cause the compilation to fail because it is still using support library.
