### ISSUE TITLE
帐号绑定 bindAccount 可能有问题

### ISSUE THREAD

**Issue by Doflatango** [v7lin/fake_push#19]
下面遇到的问题和测试的过程：
1. 在 receiveDeviceToken 回调里面调用 bindAccount，没有看到 error 所以不知道是否成功；
> 可以确定的是已经收到注册 token 成功的消息，并且传入 bindAccount 的帐号是有值的。
2. 使用信鸽的 HTTP API 查询绑定的帐号，无结果；
3. 尝试使用 HTTP API 绑定帐号，成功；

平台是 Android。

**Comment by Doflatango** [comment]
刚调试了一下，发现这个应该是信鸽 SDK 的问题。
对 Android 不太熟悉，PR 中有不对的欢迎指正。

**Comment by v7lin** [comment]
👌，我会抽空验证一下这个问题 … 不过，这个pr只修改了Android部分，没有对iOS部分作相应修改，会破坏API的一致性 …

**Comment by Doflatango** [comment]
> 👌，我会抽空验证一下这个问题 … 不过，这个pr只修改了Android部分，没有对iOS部分作相应修改，会破坏API的一致性 …

iOS 那部分我没有环境可以测试，所以暂时没有办法处理。
