### ISSUE TITLE
cannot find symbol： NotificationManagerCompat 

### ISSUE THREAD

**Issue by zileyuan** [v7lin/fake_push#2]
cannot find symbol
import android.support.v4.app.NotificationManagerCompat;   

flutter 1.2.1

**Comment by v7lin** [comment]
你的项目是否升级了 AndroidX ？

**Comment by zileyuan** [comment]
升级AndroidX了

**Comment by zileyuan** [comment]
另一个问题   D8: Program type already present: android.support.v4.app.INotificationSideChannel
其它插件也依赖了

**Comment by v7lin** [comment]
flutter版本号是多少？是1.2.1么？依赖相同的library是不会有问题的。

**Comment by zileyuan** [comment]
flutter1.2.1
apple 报错 ：Unable to find a specification for `FakeXinGePush (~> 3.3.5)` depended upon by `fake_push`

**Comment by zileyuan** [comment]
之前我用 androidx解决了  ，import androidx.core.app.NotificationManagerCompat;

**Comment by v7lin** [comment]
我已经将support依赖去除了，稍后打个tag并推送到pub上

**Comment by v7lin** [comment]
已去除support v4依赖
````
dependencies:
  fake_push: ^0.3.0+1
````
