### ISSUE TITLE
iOS13之后获取DeviceToken问题

### ISSUE THREAD

**Issue by abel123321** [v7lin/fake_push#21]
[xgpush]Current device token is {length=32,bytes=0xe7a95b942287be7ff0a612faafea6c2d...2203f6cf4ba838be}

**Comment by v7lin** [comment]
😂 年久失修了，不爱折腾信鸽了，就等统一推送出来一起玩了

**Comment by BadReese** [comment]
我也遇到一样的问题了，不打算修复了吗

**Comment by v7lin** [comment]
😂 好吧，晚上我就修复一个版本吧

**Comment by BadReese** [comment]
@v7lin 好的 谢谢

**Comment by v7lin** [comment]
@BadReese 升级到 0.5.2 了

**Comment by BadReese** [comment]
> @BadReese 升级到 0.5.2 了

非常感谢，辛苦你了
