### ISSUE TITLE
proguard error

### ISSUE THREAD

**Issue by hanabi1224** [v7lin/fake_push#25]
\build\fake_push\intermediates\consumer_proguard_file\release\proguard.txt:10:1-15: R8: Unknown option "-ignorewarning"

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithR8ForRelease'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

**Comment by v7lin** [comment]
[重复](https://github.com/v7lin/fake_push/issues/24)

**Comment by v7lin** [comment]
如你所愿 0.5.3

**Comment by hanabi1224** [comment]
@v7lin 感谢~
