### ISSUE TITLE
小米手机收不到自定义消息

### ISSUE THREAD

**Issue by TangRongji** [v7lin/fake_push#28]
发送的消息：
{
  "content": "来自信鸽的测试推送消息",
  "title": "测试推送消息",
  "vibrate": 1,
  "custom_content": {
    "clickType": 1,
    "clickContent": "https://www.baidu.com"
  }
}
其中customContent不能拿到信息

**Comment by v7lin** [comment]
请看readme

**Comment by TangRongji** [comment]
您好，是要针对不同厂商做不同的消息内容吗

> 请看readme

**Comment by TangRongji** [comment]
在Readme中没有看到关于custom_content的部分呢
> 请看readme

**Comment by v7lin** [comment]
统一

**Comment by v7lin** [comment]
通知打开应用

**Comment by TangRongji** [comment]
> 通知打开应用

应用管理中已经把应用的通知权限全都打开了

**Comment by v7lin** [comment]
大哥，readme里的通知打开应用那部分内容

**Comment by TangRongji** [comment]
> 大哥，readme里的通知打开应用那部分内容

大神，还是没解决，收不到

另外还有个问题，IOS如何去掉角标

**Comment by v7lin** [comment]
[消息点击事件以及跳转页面方法](https://xg.qq.com/docs/android_access/android_faq.html#%E6%B6%88%E6%81%AF%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6%E4%BB%A5%E5%8F%8A%E8%B7%B3%E8%BD%AC%E9%A1%B5%E9%9D%A2%E6%96%B9%E6%B3%95)

Android 消息并不会非常及时就收到，等个十五分钟到半个小时属于正常现象

**Comment by TangRongji** [comment]
> [消息点击事件以及跳转页面方法](https://xg.qq.com/docs/android_access/android_faq.html#%E6%B6%88%E6%81%AF%E7%82%B9%E5%87%BB%E4%BA%8B%E4%BB%B6%E4%BB%A5%E5%8F%8A%E8%B7%B3%E8%BD%AC%E9%A1%B5%E9%9D%A2%E6%96%B9%E6%B3%95)
> 
> Android 消息并不会非常及时就收到，等个十五分钟到半个小时属于正常现象

大佬辛苦，我在看看IOS角标的问题
