### ISSUE TITLE
手机收不到通知，求指点！

### ISSUE THREAD

**Issue by yuefeng007** [v7lin/fake_push#32]
第一次使用 flutter 集成这个信鸽推送，不太了解具体流程

本人使用作者的` example` 工程测试

首先更改  `build.gradle  `里面的key  
```
 XG_ACCESS_ID    : 'xxxxxx',
 XG_ACCESS_KEY   : 'xxxxx',
```

获取了 手机的 DeviceToken并且填写到  信鸽后台 作为测试设备 。

在信鸽后台  使用测试预览推送 ，

在后台可以看到  计划推送1   在线设备1   到达设备1  

手机这边使用  debug版本  一直没反应 （oppo手机、已开启通知权限）

**Comment by v7lin** [comment]
oppo 不走产商渠道，故而有可能会收不到消息。打开APP后应该能收到消息了。请用华为或者小米测试。

**Comment by yuefeng007** [comment]
那oppo手机 离线的 app是无法接到通知吗

**Comment by v7lin** [comment]
对的，我接入信鸽还不支持oppo和vivo的厂商渠道

**Comment by v7lin** [comment]
现在没空，等有空了我再更新一下这个库，毕竟有些年久失修了 ... 可鞥会换上阿里云推送 ...

**Comment by yuefeng007** [comment]
这个是需要 配置各自的厂商通道是吗？比如我要给华为手机推送 就得配置华为通道是吗

**Comment by v7lin** [comment]
对的，看readme

**Comment by yuefeng007** [comment]
好嘞，多谢
