### ISSUE TITLE
插件代码包含app-prefs:root=notifications_id，被苹果拒

### ISSUE THREAD

**Issue by zileyuan** [v7lin/fake_push#4]
Guideline 2.5.1 - Performance - Software Requirements

Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Specifically, your app uses the following non-public URL scheme:

app-prefs:root=notifications_id

Continuing to use or conceal non-public APIs in future submissions of this app may result in the termination of your Apple Developer account, as well as removal of all associated apps from the App Store.

Next Steps

To resolve this issue, please revise your app to provide the associated functionality using public APIs or remove the functionality using the "prefs:root" or "App-Prefs:root" URL scheme.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

Since your App Store Connect status is Metadata Rejected, we do NOT require a new binary. To revise the metadata, visit App Store Connect to select your app and revise the desired metadata values. Once you’ve completed all changes, reply to this message in Resolution Center and we will continue the review.

**Comment by v7lin** [comment]
好的

**Comment by v7lin** [comment]
网络问题，无法使用 shadowsocks 将包上传到 pub 上，先用以下方式解决
````
dependencies:
  fake_push:
    git:
      url: https://github.com/v7lin/fake_push.git
    ref: 0.3.0+2
````
