### ISSUE TITLE
flutter获取不到 token， 日志出现下面的错误

### ISSUE THREAD

**Issue by shaibaoj** [v7lin/fake_push#5]
D/TPush   (11422): 注册成功，设备token为：571a1929040647116ffbdf836f9bef85d8bb2770
E/XINGE   (11422): [XGPushManager] OperateRunnable
E/XINGE   (11422): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: tpush.working.thread
E/XINGE   (11422): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/XINGE   (11422): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/XINGE   (11422): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/XINGE   (11422): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/XINGE   (11422): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/XINGE   (11422): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/XINGE   (11422): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/XINGE   (11422): 	at io.github.v7lin.fakepush.FakePushPlugin$4.onSuccess(FakePushPlugin.java:181)
E/XINGE   (11422): 	at com.tencent.android.tpush.XGPushManager$a.run(ProGuard:2463)
E/XINGE   (11422): 	at android.os.Handler.handleCallback(Handler.java:873)
E/XINGE   (11422): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/XINGE   (11422): 	at android.os.Looper.loop(Looper.java:193)
E/XINGE   (11422): 	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by v7lin** [comment]
好的

**Comment by v7lin** [comment]
已解决 … 0.4.1 …

**Comment by shaibaoj** [comment]
咋这个插件 ，现在多页面重复初始化，离线唤醒的还不太好
建议可以看看这个 友盟的插件方案，他这两块解决比较好
https://github.com/jiangyubao/flutter_umpush

**Comment by shaibaoj** [comment]
这个是昨天问题，我的解决方案
private Handler handler = new Handler() {
        public void handleMessage(Message msg) {
        // 处理消息
        super.handleMessage(msg);
        switch (msg.what) {
            case 1:
                channel.invokeMethod(METHOD_ONREGISTEREDDEVICETOKEN, XGPushConfig.getToken(registrar.context()));
                break;
        }
    };
};

//                channel.invokeMethod(METHOD_ONREGISTEREDDEVICETOKEN, XGPushConfig.getToken(registrar.context()));
                Message msg = handler.obtainMessage();
                msg.what = 1;
                handler.sendMessage(msg);

**Comment by v7lin** [comment]
初始化一次就好，为何要重复初始化。而且，友盟推到达率不高，应用杀死后就收不到消息。API也不亲和 …

**Comment by shaibaoj** [comment]
我意思是参加他们插件的封装方式，不是说用友盟， 现在多个页面操作 得new 多个push

**Comment by v7lin** [comment]
你new一个全局对象就好了

**Comment by v7lin** [comment]
JAVA党出身，面向对象，不喜欢静态变量。
