### ISSUE TITLE
貌似厂商通道还没完善吗

### ISSUE THREAD

**Issue by chenxianqi** [v7lin/fake_push#8]
我接入了华为，小米的，杀进程没收到

**Comment by chenxianqi** [comment]
目前发现杀进程后在信鸽后台推送不到，而我去厂商后台就可以

**Comment by v7lin** [comment]
还没release

**Comment by chenxianqi** [comment]
我看到了你master分支有继承进去，但是部分相关配置还未添加，我尝试fork添加后还是不行，您大概什么时候release版本出来呢，非常感谢

**Comment by v7lin** [comment]
推送不到的原因有三个，1.稍等一会儿就到位，2.插件参数配置错了，3.后台配置错了

**Comment by v7lin** [comment]
周末我再看看有没有空，把iOS的一些逻辑弄一下就over了

**Comment by v7lin** [comment]
魅族？不接了 … 份额那么少，还不如整OPPO和vivo呢 … 不知为啥信鸽的OPPO都弄好了，居然还不加到后台去，坑 …

**Comment by chenxianqi** [comment]
估计还未完善吧，不收费，它就慢慢弄了

**Comment by zhangchengtest** [comment]
ios的现在可以用吗

**Comment by v7lin** [comment]
可以用，逻辑需要微调一下
